services:
  - type: web
    name: trackmant-backend
    runtime: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt && playwright install
    startCommand: cd backend && python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: SMTP_SERVER
        scope: run
        sync: false
      - key: SMTP_PORT
        scope: run
        sync: false
      - key: SMTP_USER
        scope: run
        sync: false
      - key: SMTP_PASS
        scope: run
        sync: false
      - key: CHECK_INTERVAL_MINUTES
        value: 5
    healthCheckPath: /docs
